<?php /**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Remove default loop
remove_action( 'genesis_loop', 'genesis_do_loop' );

add_action( 'genesis_loop', 'genesis_404' );
/**
 * This function outputs a 404 "Not Found" error message
 *
 * @since 1.6
 */
function genesis_404() { ?>
	<!-- begin glorious 404 content -->
  <section id="fourohfour">
    <div class="row">
      <div class="small-10 small-centered columns text-center">
        <img src="<?php echo get_stylesheet_directory_uri(); ?>/dist/assets/img/oops-404.gif" alt="Where am I?">
        <h1>Where... Where are we?</h1>
        <h5>You seem to be a little lost. Maybe you'll have better luck with the navigation menu above or visit our <a href="/">home page</a> to find your way.</h5>
      </div>
    </div>
  </section>

  <!-- end glorious 404 content -->
<?php

}
//* Run the Genesis loop
genesis();
